id: P009363
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18766
  title: བོད་ཀྱི་ལུས་སྦྱོང་རིགས་པ་སྨན་གྱི་ལྗོན་པ་བཞུགས་སོ།
  author: ''
  volumes:
    20db5acf9b104d99a6ba3a626522d8df:
      image_group_id: I8LS18768
      title: ''
      volume_number: 1
      total_pages: 136
